.TH ySRC 6· 2013-jan "linux" "interactive usage and navigation"

.SH NAME
.B ySRC
- efficient, flexible ascii-text content creation

.SH PATRON
.B angelia-minyma (message)
embodiment of the gods communications

.SH IMAGERY
beautiful young woman with graceful wings and feathers in her hair

.SH SUMMARY
ySRC is a custom c library providing universal vi/vim-ish ascii-text content
creation and editing -- including navigation, selection, copy registers,
undo/redo, display, and status to custom programs.

.SH SERIOUS DISCLAIMER
i'm a crazy, naive, dog-fooding c programmer.  i'm NOT trying to be best.
i optimize for learning, transparency, and ease of maintenance.  if i wanted
awesome, fast, and cutting-edge, i'd use yours ;)

.SH DOCUMENTATION FILES (see also)
.nf  
ySRC (3)           interfacing applications with library
.B ySRC (6)···········interactive usage and navigation
ySRC (7)           decision rationale, scope, and objectives
ySRC (9)           user interface behavior guarantees

.SH FILE PURPOSE
